image: ubuntu:20.04

stages:
  - test

test:
  stage: test
  script:
    - apt-get update -yq
    - DEBIAN_FRONTEND="noninteractive" apt-get -y install golang-go
    - cd src
    - go test
