image: ubuntu:18.04
stages:
  - test

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3
    - apt-get install -y python3-pip
    - pip3 install -U requests
    - cd src
    - python3 -m unittest test
