image: php

before_script:
  # install git
  - apt-get update -yqq
  - apt-get install git -yqq
  # Install composers
  - curl -sS https://getcomposer.org/installer | php

  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
  - mv phpunit.phar /usr/local/bin/phpunit

  # Install all project dependencies
  - php composer.phar install

tests:
  script:
    - phpunit src/functionTest.php
